server:
  port: 80 #服务端口

eureka:
  client:
    #    表示将自己注册到eureka服务中心去
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#
#  ReadTimeout: 6000
#
#  ConnectTimeout: 6000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.cloud.openFeign.service.paymentFeign: debug
feign:
  hystrix:
    enabled: true